name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:  # 手動実行も可能

# OIDCトークンの取得を許可
permissions:
  id-token: write   # OIDCトークン取得に必要
  contents: read    # リポジトリの読み取り

jobs:
  deploy:
    name: Deploy to S3 + CloudFront
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Deploy frontend (build, upload to S3, invalidate CloudFront)
        run: |
          chmod +x ./scripts/deploy-frontend.sh
          ./scripts/deploy-frontend.sh

      - name: Deployment summary
        if: success()
        run: |
          echo "✅ Frontend deployment successful!"
          echo "All resource information retrieved from SSM Parameter Store"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Frontend deployment failed!"
          echo "Check the logs above for details"
