name: Terraform Apply

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  workflow_dispatch:  # 手動実行も可能

# OIDCトークンの取得を許可
permissions:
  id-token: write   # OIDCトークン取得に必要
  contents: read    # リポジトリの読み取り

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production  # 承認フローを追加する場合

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Format Check
        working-directory: terraform/environments/dev
        run: terraform fmt -check -recursive || echo "⚠️ Terraform files need formatting"

      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve tfplan

      - name: Apply summary
        if: success()
        run: |
          echo "✅ Terraform apply completed successfully!"
          echo "Infrastructure has been updated"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Terraform apply failed!"
          echo "Check the logs above for details"
